name: Deploy Fineract Docker Image to EKS of Saksham

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy Fineract Docker Image to EKS of Saksham"
        options: ["Deploy Fineract to Saksham EKS"]
        required: true
        default: "Deploy Fineract to Saksham EKS"

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SAKSHAM }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SAKSHAM }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fineract
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ./gradlew :fineract-provider:clean -Djib.to.image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG :fineract-provider:jibDockerBuild -x test
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG